[package]
name = "tiles2raster"
version.workspace = true  # inherit from [workspace.package]
edition.workspace = true

[dependencies]
clap = { version = "4.6", features = ["derive", "env"] }
comfy-table = { version = "7" }
env_logger = { version = "0.11" }
geo = { path = "../../crates/geo", features = ["gdal-static"] }
indicatif = "0.18"
indicatif-log-bridge = "0.2"
inf = { path = "../../crates/inf", features = [] }
log = "0.4"
raster-tile = { path = "../../crates/raster-tile", features = ["float_png"] }
rayon = "1.12"
reqwest = { version = "0.13" }
sqlite = { path = "../../crates/sqlite", features = [] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }

[features]
