[package]
name    = "raster"
version = "0.1.0"
edition = "2021"

[dependencies]
inf = { path = "../inf", features = ["gdal"] }

num      = "0.4"
gdal     = { version = "0.17" }
gdal-sys = { version = "0.10" }
approx   = "0.5"
arrow    = { version = "52.2", optional = true }
pyo3     = { version = "0.21", optional = true }

[dev-dependencies]
test-log      = "0.2"
env_logger    = "0.11"
generic-tests = "0.1"
ctor          = "0.2"

[features]
arrow  = ["dep:arrow", "inf/arrow"]
python = ["arrow", "arrow/pyarrow", "dep:pyo3", "inf/python"]

[package.metadata.vcpkg]
dependencies = ["gdal[core,iconv]"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static" }
