[project]
authors     = ["Dirk Vanden Boer <dirk.vdb@gmail.com>"]
channels    = ["conda-forge"]
description = "Python environment for testing python bindings related code"
name        = "test_env"
platforms   = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version     = "0.1.0"

[tasks]
test_release = { cmd = "cargo nextest run --profile ci --workspace --all-features --release" }
test_debug   = "cargo nextest run --profile ci  --workspace --all-features"

[dependencies]
pyarrow = ">=19.0.0,<20"

[target.linux.activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"