[package]
name = "creatembtiles"
version.workspace = true  # inherit from [workspace.package]
edition.workspace = true

[package.metadata.vcpkg]
dependencies = ["gdal[core,netcdf]"]

[dependencies]
clap = { version = "4.6", features = ["derive", "env"] }
env_logger = { version = "0.11" }
geo = { path = "../../crates/geo", features = ["gdal-static"] }
indicatif = "0.18"
indicatif-log-bridge = "0.2"
inf = { path = "../../crates/inf", features = [] }
log = "0.4"
rayon = "1.12"
sqlite = { path = "../../crates/sqlite", features = [] }
thiserror = "2.0"
tiler = { path = "../../crates/tiler", features = [] }

[features]
