[package]
edition = "2024"
name    = "simd_macro"
version = "0.1.0"

[dependencies]
proc-macro2 = "1"
quote       = "1"
syn         = { version = "2", features = ["full"] }

[lib]
proc-macro = true

[features]
simd = []
