[env]
GDAL_STATIC = "1"
GDAL_HOME = { value = "target/vcpkg/installed/arm64-osx", relative = true }
PKG_CONFIG = { value = "target/vcpkg/installed/arm64-osx/tools/pkgconf/pkgconf", relative = true }
PKG_CONFIG_PATH = { value = "target/vcpkg/installed/arm64-osx/lib/pkgconfig", relative = true }

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static,+avx2"]