[package]
name    = "vector"
version = "0.1.0"
edition = "2021"

[dependencies]
inf           = { path = "../inf", features = ["gdal"] }
vector_derive = { path = "vector_derive", optional = true }

gdal     = { git = "https://github.com/georust/gdal.git", rev = "f59ca68ba27b3390ef1b3d28e878d821367dd6a7" } # using version from git to support gdal >= 3.8
gdal-sys = { git = "https://github.com/georust/gdal.git", rev = "f59ca68ba27b3390ef1b3d28e878d821367dd6a7" }
approx   = "0.5"

[dev-dependencies]
inf        = { path = "../inf", features = ["gdal-static"] }
path_macro = "1.0"

[features]
derive = ["dep:vector_derive"]

[package.metadata.vcpkg]
dependencies = ["gdal[core,iconv]"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static" }
