# Devenv configuration for building cargo-only without external native dependencies
[tools]
cargo-binstall = "latest"
"cargo:cargo-nextest" = "latest"

[tools.rust]
version = "1.89.0"
profile = "minimal"
targets = "wasm32-unknown-unknown{% if os() == 'macos' %},x86_64-apple-darwin{% endif %}"


[settings]
cargo.binstall = true

[tasks]
build = "cargo build -p geo --release --no-default-features --features=serde,derive,raster-io-geotiff,vector-io,polars,rayon,proj4rs"
test = "cargo nextest run -p geo --release --no-default-features --features=serde,derive,raster-io-geotiff,vector-io,polars,rayon,proj4rs"
ci = "cargo nextest run --profile ci -p geo --release --no-default-features --features=serde,derive,raster-io-geotiff,vector-io,polars,rayon,proj4rs"
