[package]
name = "cog-analyzer"
version.workspace = true
edition.workspace = true
description = "TUI tool to analyze and visualize Cloud Optimized GeoTIFF files"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
crossterm = { version = "0.29" }
env_logger = "0.11"
geo = { path = "../../crates/geo", features = [
  "gdal-static",
  "raster-io-geotiff",
] }
image = "0.25"
inf = { path = "../../crates/inf" }
log = "0.4"
ratatui = { version = "0.30", features = ["crossterm"] }
ratatui-image = { version = "11.0", default-features = false, features = [
  "image-defaults",
  "crossterm",
] }
