name: Build

on: [push]

jobs:
  compile:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest }
          - { os: windows-2022 }
          - { os: macos-latest }

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: prefix-dev/setup-pixi@v0.8.0
      - uses: taiki-e/install-action@v2
        with:
          tool: just,sd,fd-find,cargo-vcpkg,cargo-nextest
      - name: Build the C++ dependencies using vcpkg
        env: 
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: just bootstrap
      - name: Install the python environment with pixi
        run: just pybootstrap
      - name: Build the project
        run: just build
      - name: Run the unit tests
        run: just test_release
      - name: Run the unit tests with python feature enabled
        run: just test_release_py