name: Build

on: [push]

jobs:
  compile:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest }
          - { os: windows-2022 }
          - { os: macos-latest }

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: prefix-dev/setup-pixi@v0.8.0
      - uses: taiki-e/install-action@v2
        with:
          tool: just,sd,fd-find,cargo-vcpkg,cargo-nextest
      - name: Build the C++ dependencies using vcpkg
        run: just bootstrap
      - name: Install the python environment with pixi
        run: just pybootstrap
      - name: Build the project
        run: just build
      - name: Run the unit tests
        run: just test_release
      - name: Run the unit tests with python feature enabled
        run: just test_release_py
      - name: Build the docs
        run: just doc