name: Build

on: [push]

jobs:
  compile:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, id: linux  }
          - { os: windows-2025, id: windows  }
          - { os: macos-latest, id: mac  }

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: prefix-dev/setup-pixi@v0.8.0
      - uses: taiki-e/install-action@v2
        with:
          tool: just,sd,fd-find,cargo-vcpkg,cargo-nextest
      - name: Cache vcpkg packages
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            ~/AppData/Local/vcpkg/archives
          key: ${{ matrix.cfg.os }}-${{ hashFiles('Cargo.toml') }}
      - name: Build the C++ dependencies using vcpkg
        run: just bootstrap
      - name: Install the python environment with pixi
        run: just pybootstrap
      - name: Build the project
        run: just build
      - name: Run the unit tests
        run: just test_release
      - name: Run the unit tests with python feature enabled
        run: just test_release_py
      - name: Build the docs
        run: just doc
      - name: Archive build logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.id }}-build-logs
          path: |
            target/vcpkg/buildtrees/**/autoconf*.log
            target/vcpkg/buildtrees/**/config*.log
            target/vcpkg/buildtrees/**/build*.log
            target/vcpkg/buildtrees/**/install*.log
            target/vcpkg/buildtrees/**/package*.log