name: Nix build
on: [push]

jobs:
    compile:
        name: ${{ matrix.cfg.id }}
        runs-on: ${{ matrix.cfg.os }}
        strategy:
            fail-fast: false
            matrix:
                cfg:
                    - {
                          id: linux,
                          os: ubuntu-latest,
                          target: x86_64-unknown-linux-gnu,
                      }
                    - {
                          id: mac-arm,
                          os: macos-latest,
                          target: aarch64-apple-darwin,
                      }

        steps:
            - uses: actions/checkout@v6
            - uses: cachix/install-nix-action@v31
            - uses: cachix/cachix-action@v17
              with:
                  name: devenv
                  extraPullNames: geo-overlay
            - name: Install pinned devenv
              run: nix profile add --accept-flake-config github:cachix/devenv/v2.0.5
            - name: Build the project
              shell: devenv shell bash -- -e {0}
              run: just build_ci
            - name: Run the unit tests
              shell: devenv shell bash -- -e {0}
              run: just test_ci
            - name: Build the docs
              shell: devenv --profile nightly shell bash -- -e {0}
              run: just doc
